package utils;

/*import com.google.common.collect.HashMultimap;
import com.google.common.collect.Multimap;*/

/**
 * Created by Umeed-e-Nau on 12/21/2016.
 */
public class ClustorDistricts {

//    private static Multimap<String, String> data = HashMultimap.create();
//
//    public static List<String> get(String province) {
//
//
//        data.put("Badin", "SBBB1");
//        data.put("Badin", "SBBB6");
//        data.put("Badin", "SBBB8");
//        data.put("Badin", "SBBB12");
//        data.put("Badin", "SBBB22");
//        data.put("Badin", "SBBB29");
//        data.put("Badin", "SBBB34");
//        data.put("Badin", "SBBB38");
//        data.put("Badin", "SBBB40");
//        data.put("Badin", "SBBB51");
//        data.put("Badin", "SBBB55");
//        data.put("Badin", "SBBB57");
//        data.put("Badin", "SBBB71");
//        data.put("Badin", "SBBB73");
//        data.put("Badin", "SBBB86");
//        data.put("Badin", "SBBK104");
//        data.put("Badin", "SBBM114");
//        data.put("Badin", "SBBM118");
//        data.put("Badin", "SBBM124");
//        data.put("Badin", "SBBM129");
//        data.put("Badin", "SBBL137");
//        data.put("Badin", "SBBL154");
//        data.put("Badin", "SBBL156");
//        data.put("Badin", "SBBL158");
//        data.put("Badin", "SBBL159");
//        data.put("Badin", "SBBL161");
//        data.put("Badin", "SBBK167");
//        data.put("Badin", "SBBK174");
//        data.put("Badin", "SBBK180");
//        data.put("Badin", "SBBK182");
//        data.put("Badin", "SBBA207");
//        data.put("Badin", "SBBA213");
//        data.put("Badin", "SBBN226");
//        data.put("Badin", "SBBN236");
//        data.put("Badin", "SBBN240");
//        data.put("Badin", "SBBN242");
//        data.put("Badin", "SBBS248");
//        data.put("Badin", "SBBS252");
//        data.put("Badin", "SBBS258");
//        data.put("Badin", "SBBS264");
//        data.put("Badin", "SBBS267");
//        data.put("Badin", "SBBS270");
//        data.put("Badin", "SBBS275");
//        data.put("Badin", "SBMM287");
//        data.put("Badin", "SBMM297");
//        data.put("Badin", "SBMM301");
//        data.put("Badin", "SBMM303");
//        data.put("Badin", "SBMM346");
//        data.put("Badin", "SBMM356");
//        data.put("Badin", "SBMM361");
//        data.put("Badin", "SBMT373");
//        data.put("Badin", "SBMT375");
//        data.put("Badin", "SBMT376");
//        data.put("Badin", "SBMT384");
//        data.put("Badin", "SBMM403");
//        data.put("Badin", "SBMM406");
//        data.put("Badin", "SBMM412");
//        data.put("Badin", "SBMM416");
//        data.put("Badin", "SBMM428");
//        data.put("Badin", "SBMM429");
//        data.put("Badin", "SBMT442");
//        data.put("Badin", "SBMT452");
//        data.put("Badin", "SBMT458");
//        data.put("Badin", "SBMT459");
//        data.put("Badin", "SBMT470");
//        data.put("Badin", "SBMM481");
//        data.put("Badin", "SBMM495");
//        data.put("Badin", "SBMM498");
//        data.put("Badin", "SBMM506");
//        data.put("Badin", "SBMM514");
//        data.put("Badin", "SBMM515");
//        data.put("Badin", "SBMM516");
//        data.put("Badin", "SBMM517");
//        data.put("Badin", "SBMM518");
//        data.put("Badin", "SBMM521");
//        data.put("Badin", "SBMM526");
//        data.put("Badin", "SBMM534");
//        data.put("Badin", "SBMM536");
//        data.put("Badin", "SBMM538");
//        data.put("Badin", "SBMM550");
//        data.put("Badin", "SBMD562");
//        data.put("Badin", "SBMP580");
//        data.put("Badin", "SBMP581");
//        data.put("Badin", "SBMP584");
//        data.put("Badin", "SBMB614");
//        data.put("Badin", "SBMB615");
//        data.put("Badin", "SBMB618");
//        data.put("Badin", "SBMB624");
//        data.put("Badin", "SBMB629");
//        data.put("Badin", "SBMB631");
//        data.put("Badin", "SBMB637");
//        data.put("Badin", "SBMB645");
//        data.put("Badin", "SBMB648");
//        data.put("Badin", "SBMB651");
//        data.put("Badin", "SBTT657");
//        data.put("Badin", "SBTT661");
//        data.put("Badin", "SBTT668");
//        data.put("Badin", "SBTT670");
//        data.put("Badin", "SBTT672");
//        data.put("Badin", "SBTT680");
//        data.put("Badin", "SBTT697");
//        data.put("Badin", "SBTT700");
//        data.put("Badin", "SBTS708");
//        data.put("Badin", "SBTS709");
//        data.put("Badin", "SBTS722");
//        data.put("Badin", "SBTS725");
//        data.put("Badin", "SBTS727");
//        data.put("Badin", "SBTS729");
//        data.put("Badin", "SBTR734");
//        data.put("Badin", "SBTR735");
//        data.put("Badin", "SBTR743");
//        data.put("Badin", "SBTR755");
//        data.put("Badin", "SBTR770");
//        data.put("Badin", "SBTP783");
//        data.put("Badin", "SBTP785");
//        data.put("Badin", "SBTP787");
//        data.put("Badin", "SBTP814");
//        data.put("Badin", "SBTT817");
//        data.put("Badin", "SBTT832");
//        data.put("Badin", "SBTT838");
//        data.put("Badin", "SBTC852");
//        data.put("Badin", "SBTC855");
//        data.put("Badin", "SBTC857");
//        data.put("Badin", "SBTK862");
//        data.put("Badin", "SBTK863");
//        data.put("Badin", "SBTK880");
//        data.put("Badin", "SBTK893");
//        data.put("Badin", "SBTK896");
//        data.put("Badin", "SBTK897");
//        data.put("Badin", "SBTD912");
//        data.put("Badin", "SBTD913");
//        data.put("Badin", "SBTD914");
//        data.put("Badin", "SBTD918");
//        data.put("Badin", "SBTP922");
//        data.put("Badin", "SBTP923");
//        data.put("Badin", "SBTP924");
//        data.put("Badin", "SBTP929");
//        data.put("Badin", "SBTP952");
//        data.put("Badin", "SBTP953");
//        data.put("Badin", "SBTD967");
//        data.put("Badin", "SBTD969");
//        data.put("Badin", "SBTD976");
//        data.put("Badin", "SBTK994");
//        data.put("Badin", "SBTK996");
//        data.put("Badin", "SBTP1007");
//        data.put("Badin", "SBTP1009");
//        data.put("Badin", "SBTP1012");
//        data.put("Badin", "SBTK1016");
//        data.put("Badin", "SBTK1017");
//        data.put("Badin", "SBTK1023");
//
//        //**************** Badin Unvorerd********************************//
//
//
//        data.put("Badin", "SBBM151");
//        data.put("Badin", "SBGA152");
//        data.put("Badin", "SBMH153");
//        data.put("Badin", "SBMH154");
//        data.put("Badin", "SBMH155");
//        data.put("Badin", "SBGR156");
//        data.put("Badin", "SBGG157");
//        data.put("Badin", "SBBK158");
//        data.put("Badin", "SBBM159");
//        data.put("Badin", "SBGG160");
//        data.put("Badin", "SBGG161");
//        data.put("Badin", "SBbB162");
//        data.put("Badin", "SBTK163");
//        data.put("Badin", "SBBM164");
//        data.put("Badin", "SBBA165");
//        data.put("Badin", "SBMP166");
//        data.put("Badin", "SBGA167");
//        data.put("Badin", "SBBM168");
//        data.put("Badin", "SBGG169");
//        data.put("Badin", "SBBK170");
//        data.put("Badin", "SBBK171");
//        data.put("Badin", "SBGA172");
//        data.put("Badin", "SBTK173");
//        data.put("Badin", "SBBK251");
//        data.put("Badin", "SBMG175");
//        data.put("Badin", "SBBB176");
//        data.put("Badin", "SBBB177");
//        data.put("Badin", "SBGK178");
//        data.put("Badin", "SBGD179");
//        data.put("Badin", "SBMG180");
//        data.put("Badin", "SBGD181");
//        data.put("Badin", "SBBM182");
//        data.put("Badin", "SBGK183");
//        data.put("Badin", "SBMP184");
//        data.put("Badin", "SBTP185");
//        data.put("Badin", "SBBS186");
//        data.put("Badin", "SBMD187");
//        data.put("Badin", "SBBM188");
//        data.put("Badin", "SBTK189");
//        data.put("Badin", "SBGG190");
//        data.put("Badin", "SBTP191");
//        data.put("Badin", "SBTK192");
//        data.put("Badin", "SBTK193");
//        data.put("Badin", "SBBM194");
//        data.put("Badin", "SBGA195");
//        data.put("Badin", "SBBB196");
//        data.put("Badin", "SBTD197");
//        data.put("Badin", "SBBS198");
//        data.put("Badin", "SBMG199");
//        data.put("Badin", "SBTD200");
//        data.put("Badin", "SBTK201");
//        data.put("Badin", "SBGG202");
//        data.put("Badin", "SBBS203");
//        data.put("Badin", "SBMH204");
//        data.put("Badin", "SBBM205");
//        data.put("Badin", "SBMM206");
//        data.put("Badin", "SBGG207");
//        data.put("Badin", "SBGT208");
//        data.put("Badin", "SBGD209");
//        data.put("Badin", "SBGD210");
//        data.put("Badin", "SBGR211");
//        data.put("Badin", "SBGK212");
//        data.put("Badin", "SBGT213");
//        data.put("Badin", "SBTK214");
//        data.put("Badin", "SBMB215");
//        data.put("Badin", "SBGA216");
//        data.put("Badin", "SBGG217");
//        data.put("Badin", "SBGG218");
//        data.put("Badin", "SBMP219");
//        data.put("Badin", "SBBK220");
//        data.put("Badin", "SBBM221");
//        data.put("Badin", "SBGD222");
//        data.put("Badin", "SBGR223");
//        data.put("Badin", "SBTK224");
//        data.put("Badin", "SBMH225");
//        data.put("Badin", "SBTC226");
//        data.put("Badin", "SBGG227");
//        data.put("Badin", "SBMM228");
//        data.put("Badin", "SBBM229");
//        data.put("Badin", "SBGD230");
//        data.put("Badin", "SBGA231");
//        data.put("Badin", "SBGD232");
//        data.put("Badin", "SBTK233");
//        data.put("Badin", "SBMH234");
//        data.put("Badin", "SBMH235");
//        data.put("Badin", "SBMG236");
//        data.put("Badin", "SBBM237");
//        data.put("Badin", "SBMB238");
//        data.put("Badin", "SBBM239");
//        data.put("Badin", "SBBK240");
//        data.put("Badin", "SBMH241");
//        data.put("Badin", "SBGD242");
//        data.put("Badin", "SBBB243");
//        data.put("Badin", "SBGD244");
//        data.put("Badin", "SBGA245");
//        data.put("Badin", "SBTK246");
//        data.put("Badin", "SBMH247");
//        data.put("Badin", "SBTC248");
//        data.put("Badin", "SBMD249");
//        data.put("Badin", "SBTK250");
//
//
//        //***********************************************************************//
//
//
//        data.put("Sanghar", "SSSC1");
//        data.put("Sanghar", "SSTP2");
//        data.put("Sanghar", "SSSC3");
//        data.put("Sanghar", "SSSG4");
//        data.put("Sanghar", "SSSB5");
//        data.put("Sanghar", "SSSS6");
//        data.put("Sanghar", "SSSS7");
//        data.put("Sanghar", "SSSJ8");
//        data.put("Sanghar", "SSSS9");
//        data.put("Sanghar", "SSSS10");
//        data.put("Sanghar", "SSSJ11");
//        data.put("Sanghar", "SSSK12");
//        data.put("Sanghar", "SSSS13");
//        data.put("Sanghar", "SSSK14");
//        data.put("Sanghar", "SSSA15");
//        data.put("Sanghar", "SSTT16");
//        data.put("Sanghar", "SSTT17");
//        data.put("Sanghar", "SSSA18");
//        data.put("Sanghar", "SSSK19");
//        data.put("Sanghar", "SSSS20");
//        data.put("Sanghar", "SSTT21");
//        data.put("Sanghar", "SSSL22");
//        data.put("Sanghar", "SSSS23");
//        data.put("Sanghar", "SSSK24");
//        data.put("Sanghar", "SSSS25");
//        data.put("Sanghar", "SSTT26");
//        data.put("Sanghar", "SSSS27");
//        data.put("Sanghar", "SSSM28");
//        data.put("Sanghar", "SSSS29");
//        data.put("Sanghar", "SSTK30");
//        data.put("Sanghar", "SSSS31");
//        data.put("Sanghar", "SSSJ32");
//        data.put("Sanghar", "SSSJ33");
//        data.put("Sanghar", "SSTT34");
//        data.put("Sanghar", "SSSK35");
//        data.put("Sanghar", "SSTM36");
//        data.put("Sanghar", "SSSJ37");
//        data.put("Sanghar", "SSTT38");
//        data.put("Sanghar", "SSSS39");
//        data.put("Sanghar", "SSSS40");
//        data.put("Sanghar", "SSSJ41");
//        data.put("Sanghar", "SSSM42");
//        data.put("Sanghar", "SSSS43");
//        data.put("Sanghar", "SSSM44");
//        data.put("Sanghar", "SSSB45");
//        data.put("Sanghar", "SSTM46");
//        data.put("Sanghar", "SSTP47");
//        data.put("Sanghar", "SSTT48");
//        data.put("Sanghar", "SSSK49");
//        data.put("Sanghar", "SSSG50");
//        data.put("Sanghar", "SSSG51");
//        data.put("Sanghar", "SSSA52");
//        data.put("Sanghar", "SSSP53");
//        data.put("Sanghar", "SSSS54");
//        data.put("Sanghar", "SSSS55");
//        data.put("Sanghar", "SSSS56");
//        data.put("Sanghar", "SSSG57");
//        data.put("Sanghar", "SSTT58");
//        data.put("Sanghar", "SSSJ59");
//        data.put("Sanghar", "SSSJ60");
//        data.put("Sanghar", "SSSS61");
//        data.put("Sanghar", "SSTT62");
//        data.put("Sanghar", "SSSS63");
//        data.put("Sanghar", "SSTT64");
//        data.put("Sanghar", "SSSP65");
//        data.put("Sanghar", "SSSL66");
//        data.put("Sanghar", "SSSS67");
//        data.put("Sanghar", "SSSG68");
//        data.put("Sanghar", "SSSJ69");
//        data.put("Sanghar", "SSSS70");
//        data.put("Sanghar", "SSSJ71");
//        data.put("Sanghar", "SSSS72");
//        data.put("Sanghar", "SSSK73");
//        data.put("Sanghar", "SSSL74");
//        data.put("Sanghar", "SSTT75");
//        data.put("Sanghar", "SSSS76");
//        data.put("Sanghar", "SSSS77");
//        data.put("Sanghar", "SSTT78");
//        data.put("Sanghar", "SSSS79");
//        data.put("Sanghar", "SSSM80");
//        data.put("Sanghar", "SSSG81");
//        data.put("Sanghar", "SSSS82");
//        data.put("Sanghar", "SSSL83");
//        data.put("Sanghar", "SSTT84");
//        data.put("Sanghar", "SSSS85");
//        data.put("Sanghar", "SSTT86");
//        data.put("Sanghar", "SSSA87");
//        data.put("Sanghar", "SSSG88");
//        data.put("Sanghar", "SSSS89");
//        data.put("Sanghar", "SSSB90");
//        data.put("Sanghar", "SSSS91");
//        data.put("Sanghar", "SSSM92");
//        data.put("Sanghar", "SSSS93");
//        data.put("Sanghar", "SSSG94");
//        data.put("Sanghar", "SSTT95");
//        data.put("Sanghar", "SSSS96");
//        data.put("Sanghar", "SSTK97");
//        data.put("Sanghar", "SSSS98");
//        data.put("Sanghar", "SSSS99");
//        data.put("Sanghar", "SSTM100");
//        data.put("Sanghar", "SSSK101");
//        data.put("Sanghar", "SSSS102");
//        data.put("Sanghar", "SSSS103");
//        data.put("Sanghar", "SSSS104");
//        data.put("Sanghar", "SSSL105");
//        data.put("Sanghar", "SSSJ106");
//        data.put("Sanghar", "SSSS107");
//        data.put("Sanghar", "SSSS108");
//        data.put("Sanghar", "SSSS109");
//        data.put("Sanghar", "SSTP110");
//        data.put("Sanghar", "SSSK111");
//        data.put("Sanghar", "SSSS112");
//        data.put("Sanghar", "SSSC113");
//        data.put("Sanghar", "SSSA114");
//        data.put("Sanghar", "SSSA115");
//        data.put("Sanghar", "SSSK116");
//        data.put("Sanghar", "SSSM117");
//        data.put("Sanghar", "SSSP118");
//        data.put("Sanghar", "SSTK119");
//        data.put("Sanghar", "SSSM120");
//        data.put("Sanghar", "SSSS121");
//        data.put("Sanghar", "SSTK122");
//        data.put("Sanghar", "SSSK123");
//        data.put("Sanghar", "SSTK124");
//        data.put("Sanghar", "SSTK125");
//        data.put("Sanghar", "SSSS126");
//        data.put("Sanghar", "SSSB127");
//        data.put("Sanghar", "SSSJ128");
//        data.put("Sanghar", "SSTM129");
//        data.put("Sanghar", "SSSK130");
//        data.put("Sanghar", "SSSJ131");
//        data.put("Sanghar", "SSSS132");
//        data.put("Sanghar", "SSSK133");
//        data.put("Sanghar", "SSSK134");
//        data.put("Sanghar", "SSTM135");
//        data.put("Sanghar", "SSSS136");
//        data.put("Sanghar", "SSSK137");
//        data.put("Sanghar", "SSSS138");
//        data.put("Sanghar", "SSSS139");
//        data.put("Sanghar", "SSSM140");
//        data.put("Sanghar", "SSSS141");
//        data.put("Sanghar", "SSSJ142");
//        data.put("Sanghar", "SSTT143");
//        data.put("Sanghar", "SSTT144");
//        data.put("Sanghar", "SSSS145");
//        data.put("Sanghar", "SSTM146");
//        data.put("Sanghar", "SSSS147");
//        data.put("Sanghar", "SSSS148");
//        data.put("Sanghar", "SSSP149");
//        data.put("Sanghar", "SSSK150");
//
//
//        /////// Sangar Uncoverd////////////////
//
//
//        data.put("Sanghar", "SSSS151");
//        data.put("Sanghar", "SSKB152");
//        data.put("Sanghar", "SSJH153");
//        data.put("Sanghar", "SSSL154");
//        data.put("Sanghar", "SSSJ155");
//        data.put("Sanghar", "SSTM156");
//        data.put("Sanghar", "SSSS157");
//        data.put("Sanghar", "SSSC158");
//        data.put("Sanghar", "SSSK159");
//        data.put("Sanghar", "SSSS160");
//        data.put("Sanghar", "SSJB161");
//        data.put("Sanghar", "SSSJ162");
//        data.put("Sanghar", "SSSA163");
//        data.put("Sanghar", "SSSL164");
//        data.put("Sanghar", "SSSK165");
//        data.put("Sanghar", "SSSC166");
//        data.put("Sanghar", "SSTT167");
//        data.put("Sanghar", "SSKK168");
//        data.put("Sanghar", "SSSS169");
//        data.put("Sanghar", "SSSC170");
//        data.put("Sanghar", "SSTM171");
//        data.put("Sanghar", "SSTM172");
//        data.put("Sanghar", "SSKK173");
//        data.put("Sanghar", "SSSK174");
//        data.put("Sanghar", "SSSJ175");
//        data.put("Sanghar", "SSSJ176");
//        data.put("Sanghar", "SSSS177");
//        data.put("Sanghar", "SSTM178");
//        data.put("Sanghar", "SSJB179");
//        data.put("Sanghar", "SSKK180");
//        data.put("Sanghar", "SSSS181");
//        data.put("Sanghar", "SSSK182");
//        data.put("Sanghar", "SSSC183");
//        data.put("Sanghar", "SSSS184");
//        data.put("Sanghar", "SSTT185");
//        data.put("Sanghar", "SSJB186");
//        data.put("Sanghar", "SSJJ187");
//        data.put("Sanghar", "SSTM188");
//        data.put("Sanghar", "SSKJ189");
//        data.put("Sanghar", "SSSJ190");
//        data.put("Sanghar", "SSSP191");
//        data.put("Sanghar", "SSSJ192");
//        data.put("Sanghar", "SSSJ193");
//        data.put("Sanghar", "SSTP194");
//        data.put("Sanghar", "SSTT195");
//        data.put("Sanghar", "SSKK196");
//        data.put("Sanghar", "SSSS197");
//        data.put("Sanghar", "SSTT198");
//        data.put("Sanghar", "SSSS199");
//        data.put("Sanghar", "SSTM200");
//        data.put("Sanghar", "SSSJ201");
//        data.put("Sanghar", "SSJH202");
//        data.put("Sanghar", "SSSP203");
//        data.put("Sanghar", "SSSJ204");
//        data.put("Sanghar", "SSKR205");
//        data.put("Sanghar", "SSKK206");
//        data.put("Sanghar", "SSKH207");
//        data.put("Sanghar", "SSSG208");
//        data.put("Sanghar", "SSSK209");
//        data.put("Sanghar", "SSSJ210");
//        data.put("Sanghar", "SSSS211");
//        data.put("Sanghar", "SSSJ212");
//        data.put("Sanghar", "SSSK213");
//        data.put("Sanghar", "SSTM214");
//        data.put("Sanghar", "SSSJ215");
//        data.put("Sanghar", "SSSS216");
//        data.put("Sanghar", "SSKB217");
//        data.put("Sanghar", "SSSS218");
//        data.put("Sanghar", "SSKD219");
//        data.put("Sanghar", "SSTM220");
//        data.put("Sanghar", "SSTM221");
//        data.put("Sanghar", "SSSJ222");
//        data.put("Sanghar", "SSSK223");
//        data.put("Sanghar", "SSSS224");
//        data.put("Sanghar", "SSSK225");
//        data.put("Sanghar", "SSSJ226");
//        data.put("Sanghar", "SSTM227");
//        data.put("Sanghar", "SSSS228");
//        data.put("Sanghar", "SSSK229");
//        data.put("Sanghar", "SSKK230");
//        data.put("Sanghar", "SSKB231");
//        data.put("Sanghar", "SSSG232");
//        data.put("Sanghar", "SSSK233");
//        data.put("Sanghar", "SSSK234");
//        data.put("Sanghar", "SSSK235");
//        data.put("Sanghar", "SSKK236");
//        data.put("Sanghar", "SSJB237");
//        data.put("Sanghar", "SSSK238");
//        data.put("Sanghar", "SSTM239");
//        data.put("Sanghar", "SSSK240");
//        data.put("Sanghar", "SSTT241");
//        data.put("Sanghar", "SSSS242");
//        data.put("Sanghar", "SSSP243");
//        data.put("Sanghar", "SSSM244");
//        data.put("Sanghar", "SSSS245");
//        data.put("Sanghar", "SSTK246");
//        data.put("Sanghar", "SSKD247");
//        data.put("Sanghar", "SSTM248");
//        data.put("Sanghar", "SSSK249");
//        data.put("Sanghar", "SSSS250");
//
//
//        //////////////////////////////////////////////////////////////////////////////////
//
//
//        data.put("Lasbella", "BLUU1");
//        data.put("Lasbella", "BLBB2");
//        data.put("Lasbella", "BLBB3");
//        data.put("Lasbella", "BLHS4");
//        data.put("Lasbella", "BLBk5");
//        data.put("Lasbella", "BLUW6");
//        data.put("Lasbella", "BLHA7");
//        data.put("Lasbella", "BLBB8");
//        data.put("Lasbella", "BLBB9");
//        data.put("Lasbella", "BLHB10");
//        data.put("Lasbella", "BLBW11");
//        data.put("Lasbella", "BLBB12");
//        data.put("Lasbella", "BLSw13");
//        data.put("Lasbella", "BLHB14");
//        data.put("Lasbella", "BLUU15");
//        data.put("Lasbella", "BLBB16");
//        data.put("Lasbella", "BLHB17");
//        data.put("Lasbella", "BLBG18");
//        data.put("Lasbella", "BLBB19");
//        data.put("Lasbella", "BLBW20");
//        data.put("Lasbella", "BLBW21");
//        data.put("Lasbella", "BLBB22");
//        data.put("Lasbella", "BLUU23");
//        data.put("Lasbella", "BLBG24");
//        data.put("Lasbella", "BLBB25");
//        data.put("Lasbella", "BLHP26");
//        data.put("Lasbella", "BLBB27");
//        data.put("Lasbella", "BLUW28");
//        data.put("Lasbella", "BLUU29");
//        data.put("Lasbella", "BLBk30");
//        data.put("Lasbella", "BLBB31");
//        data.put("Lasbella", "BLBk32");
//        data.put("Lasbella", "BLHA33");
//        data.put("Lasbella", "BLBB34");
//        data.put("Lasbella", "BLHB35");
//        data.put("Lasbella", "BLUU36");
//        data.put("Lasbella", "BLSs37");
//        data.put("Lasbella", "BLBW38");
//        data.put("Lasbella", "BLHP39");
//        data.put("Lasbella", "BLBB40");
//        data.put("Lasbella", "BLUW41");
//        data.put("Lasbella", "BLBB42");
//        data.put("Lasbella", "BLHP43");
//        data.put("Lasbella", "BLSs44");
//        data.put("Lasbella", "BLHA45");
//        data.put("Lasbella", "BLBk46");
//        data.put("Lasbella", "BLHP47");
//        data.put("Lasbella", "BLBG48");
//        data.put("Lasbella", "BLBW49");
//        data.put("Lasbella", "BLHP50");
//        data.put("Lasbella", "BLSw51");
//        data.put("Lasbella", "BLBk52");
//        data.put("Lasbella", "BLHA53");
//        data.put("Lasbella", "BLBB54");
//        data.put("Lasbella", "BLBG55");
//        data.put("Lasbella", "BLSw56");
//        data.put("Lasbella", "BLHB57");
//        data.put("Lasbella", "BLBW58");
//        data.put("Lasbella", "BLBk59");
//        data.put("Lasbella", "BLHB60");
//        data.put("Lasbella", "BLBB61");
//        data.put("Lasbella", "BLHA62");
//        data.put("Lasbella", "BLUU63");
//        data.put("Lasbella", "BLBW64");
//        data.put("Lasbella", "BLBk65");
//        data.put("Lasbella", "BLHA66");
//        data.put("Lasbella", "BLHB67");
//        data.put("Lasbella", "BLBG68");
//        data.put("Lasbella", "BLBB69");
//        data.put("Lasbella", "BLHB70");
//        data.put("Lasbella", "BLUU71");
//        data.put("Lasbella", "BLBW72");
//        data.put("Lasbella", "BLBB73");
//        data.put("Lasbella", "BLHP74");
//        data.put("Lasbella", "BLHA75");
//        data.put("Lasbella", "BLHB76");
//        data.put("Lasbella", "BLBk77");
//        data.put("Lasbella", "BLUK78");
//        data.put("Lasbella", "BLUU79");
//        data.put("Lasbella", "BLHB80");
//        data.put("Lasbella", "BLUU81");
//        data.put("Lasbella", "BLHA82");
//        data.put("Lasbella", "BLUW83");
//        data.put("Lasbella", "BLBB84");
//        data.put("Lasbella", "BLBB85");
//        data.put("Lasbella", "BLBB86");
//        data.put("Lasbella", "BLHB87");
//        data.put("Lasbella", "BLUU88");
//        data.put("Lasbella", "BLBB89");
//        data.put("Lasbella", "BLHP90");
//        data.put("Lasbella", "BLUU91");
//        data.put("Lasbella", "BLSs92");
//        data.put("Lasbella", "BLHB93");
//        data.put("Lasbella", "BLHG94");
//        data.put("Lasbella", "BLBB95");
//        data.put("Lasbella", "BLBG96");
//        data.put("Lasbella", "BLSw97");
//        data.put("Lasbella", "BLBk98");
//        data.put("Lasbella", "BLBB99");
//        data.put("Lasbella", "BLSs100");
//        data.put("Lasbella", "BLHB101");
//        data.put("Lasbella", "BLBG102");
//        data.put("Lasbella", "BLSw103");
//        data.put("Lasbella", "BLHA104");
//        data.put("Lasbella", "BLBG105");
//        data.put("Lasbella", "BLHG106");
//        data.put("Lasbella", "BLSw107");
//        data.put("Lasbella", "BLBB108");
//        data.put("Lasbella", "BLHA109");
//        data.put("Lasbella", "BLHB110");
//        data.put("Lasbella", "BLHB111");
//        data.put("Lasbella", "BLUU112");
//        data.put("Lasbella", "BLBW113");
//        data.put("Lasbella", "BLUU114");
//        data.put("Lasbella", "BLHP115");
//        data.put("Lasbella", "BLHB116");
//        data.put("Lasbella", "BLHP117");
//        data.put("Lasbella", "BLBW118");
//        data.put("Lasbella", "BLBW119");
//        data.put("Lasbella", "BLBW120");
//        data.put("Lasbella", "BLSs121");
//        data.put("Lasbella", "BLHB122");
//        data.put("Lasbella", "BLBW123");
//        data.put("Lasbella", "BLUU124");
//        data.put("Lasbella", "BLSs125");
//        data.put("Lasbella", "BLSw126");
//        data.put("Lasbella", "BLHB127");
//        data.put("Lasbella", "BLBB128");
//        data.put("Lasbella", "BLBW129");
//        data.put("Lasbella", "BLBB130");
//        data.put("Lasbella", "BLUU131");
//        data.put("Lasbella", "BLUU132");
//        data.put("Lasbella", "BLSw133");
//        data.put("Lasbella", "BLHP134");
//        data.put("Lasbella", "BLUU135");
//        data.put("Lasbella", "BLBk136");
//        data.put("Lasbella", "BLHB137");
//        data.put("Lasbella", "BLUU138");
//        data.put("Lasbella", "BLBW139");
//        data.put("Lasbella", "BLSw140");
//        data.put("Lasbella", "BLUU141");
//        data.put("Lasbella", "BLUU142");
//        data.put("Lasbella", "BLBW143");
//        data.put("Lasbella", "BLSw144");
//        data.put("Lasbella", "BLHB145");
//        data.put("Lasbella", "BLHB146");
//        data.put("Lasbella", "BLSw147");
//        data.put("Lasbella", "BLUW148");
//        data.put("Lasbella", "BLHB149");
//        data.put("Lasbella", "BLBB150");
//
//        data.put("Lasbella", "BLBW151");
//        data.put("Lasbella", "BLBK152");
//        data.put("Lasbella", "BLHH153");
//        data.put("Lasbella", "BLHK154");
//        data.put("Lasbella", "BLSM155");
//        data.put("Lasbella", "BLHH156");
//        data.put("Lasbella", "BLHH157");
//        data.put("Lasbella", "BLLL158");
//        data.put("Lasbella", "BLLL159");
//        data.put("Lasbella", "BLBA160");
//        data.put("Lasbella", "BLBW161");
//        data.put("Lasbella", "BLLL162");
//        data.put("Lasbella", "BLHA163");
//        data.put("Lasbella", "BLBA164");
//        data.put("Lasbella", "BLHH165");
//        data.put("Lasbella", "BLLL166");
//        data.put("Lasbella", "BLBJ167");
//        data.put("Lasbella", "BLHH168");
//        data.put("Lasbella", "BLBW169");
//        data.put("Lasbella", "BLBK170");
//        data.put("Lasbella", "BLUk171");
//        data.put("Lasbella", "BLHG172");
//        data.put("Lasbella", "BLHK173");
//        data.put("Lasbella", "BLBK174");
//        data.put("Lasbella", "BLBK175");
//        data.put("Lasbella", "BLBA176");
//        data.put("Lasbella", "BLUk177");
//        data.put("Lasbella", "BLHA178");
//        data.put("Lasbella", "BLLL179");
//        data.put("Lasbella", "BLHK180");
//        data.put("Lasbella", "BLSM181");
//        data.put("Lasbella", "BLHK182");
//        data.put("Lasbella", "BLLL183");
//        data.put("Lasbella", "BLLL184");
//        data.put("Lasbella", "BLLL185");
//        data.put("Lasbella", "BLUk186");
//        data.put("Lasbella", "BLHK187");
//        data.put("Lasbella", "BLBK188");
//        data.put("Lasbella", "BLSM189");
//        data.put("Lasbella", "BLLL190");
//        data.put("Lasbella", "BLHH191");
//        data.put("Lasbella", "BLHH192");
//        data.put("Lasbella", "BLBA193");
//        data.put("Lasbella", "BLHK194");
//        data.put("Lasbella", "BLBA195");
//        data.put("Lasbella", "BLBA196");
//        data.put("Lasbella", "BLHK197");
//        data.put("Lasbella", "BLHK198");
//        data.put("Lasbella", "BLUk199");
//        data.put("Lasbella", "BLUk200");
//        data.put("Lasbella", "BLBA201");
//        data.put("Lasbella", "BLHH202");
//        data.put("Lasbella", "BLHH203");
//        data.put("Lasbella", "BLBK204");
//        data.put("Lasbella", "BLBW205");
//        data.put("Lasbella", "BLHH206");
//        data.put("Lasbella", "BLBK207");
//        data.put("Lasbella", "BLHK208");
//        data.put("Lasbella", "BLSM209");
//        data.put("Lasbella", "BLBA210");
//        data.put("Lasbella", "BLUk211");
//        data.put("Lasbella", "BLBW212");
//        data.put("Lasbella", "BLBW213");
//        data.put("Lasbella", "BLLL214");
//        data.put("Lasbella", "BLBK215");
//        data.put("Lasbella", "BLLL216");
//        data.put("Lasbella", "BLHK217");
//        data.put("Lasbella", "BLUk218");
//        data.put("Lasbella", "BLLL219");
//        data.put("Lasbella", "BLLL220");
//        data.put("Lasbella", "BLLL221");
//        data.put("Lasbella", "BLBJ222");
//        data.put("Lasbella", "BLBK223");
//        data.put("Lasbella", "BLHK224");
//        data.put("Lasbella", "BLUk225");
//        data.put("Lasbella", "BLSM226");
//        data.put("Lasbella", "BLLL227");
//        data.put("Lasbella", "BLBA228");
//        data.put("Lasbella", "BLBA229");
//        data.put("Lasbella", "BLUk230");
//        data.put("Lasbella", "BLLL231");
//        data.put("Lasbella", "BLSM232");
//        data.put("Lasbella", "BLBW233");
//        data.put("Lasbella", "BLBW234");
//        data.put("Lasbella", "BLLL235");
//        data.put("Lasbella", "BLHH236");
//        data.put("Lasbella", "BLBA237");
//        data.put("Lasbella", "BLLL238");
//        data.put("Lasbella", "BLSM239");
//        data.put("Lasbella", "BLHH240");
//        data.put("Lasbella", "BLBA241");
//        data.put("Lasbella", "BLHK242");
//        data.put("Lasbella", "BLHK243");
//        data.put("Lasbella", "BLBW244");
//        data.put("Lasbella", "BLBA245");
//        data.put("Lasbella", "BLLL246");
//        data.put("Lasbella", "BLBK247");
//        data.put("Lasbella", "BLLL248");
//        data.put("Lasbella", "BLSM249");
//        data.put("Lasbella", "BLUk250");
//
//
//        ////// UnCoverdlist ////////////////////////////////
//
//
///////////////////////////////////////////////////////////////////////////////////
//
//        data.put("Rahim yar Khan", "PRLM1");
//        data.put("Rahim yar Khan", "PRKM2");
//        data.put("Rahim yar Khan", "PRK43");
//        data.put("Rahim yar Khan", "PRS24");
//        data.put("Rahim yar Khan", "PRSR5");
//        data.put("Rahim yar Khan", "PRKM6");
//        data.put("Rahim yar Khan", "PRS27");
//        data.put("Rahim yar Khan", "PRRC8");
//        data.put("Rahim yar Khan", "PRRC9");
//        data.put("Rahim yar Khan", "PRSR10");
//        data.put("Rahim yar Khan", "PRKB11");
//        data.put("Rahim yar Khan", "PRSS12");
//        data.put("Rahim yar Khan", "PRLP13");
//        data.put("Rahim yar Khan", "PRRH14");
//        data.put("Rahim yar Khan", "PRKA15");
//        data.put("Rahim yar Khan", "PRKc16");
//        data.put("Rahim yar Khan", "PRKA17");
//        data.put("Rahim yar Khan", "PRRT18");
//        data.put("Rahim yar Khan", "PRRA19");
//        data.put("Rahim yar Khan", "PRKM20");
//        data.put("Rahim yar Khan", "PRKM21");
//        data.put("Rahim yar Khan", "PRRM22");
//        data.put("Rahim yar Khan", "PRSA23");
//        data.put("Rahim yar Khan", "PRKM24");
//        data.put("Rahim yar Khan", "PRRS25");
//        data.put("Rahim yar Khan", "PRK726");
//        data.put("Rahim yar Khan", "PRKM27");
//        data.put("Rahim yar Khan", "PRLK28");
//        data.put("Rahim yar Khan", "PRRA29");
//        data.put("Rahim yar Khan", "PRRB30");
//        data.put("Rahim yar Khan", "PRLK31");
//        data.put("Rahim yar Khan", "PRLG32");
//        data.put("Rahim yar Khan", "PRK733");
//        data.put("Rahim yar Khan", "PRK734");
//        data.put("Rahim yar Khan", "PRLc35");
//        data.put("Rahim yar Khan", "PRRA36");
//        data.put("Rahim yar Khan", "PRRC37");
//        data.put("Rahim yar Khan", "PRRC38");
//        data.put("Rahim yar Khan", "PRKM39");
//        data.put("Rahim yar Khan", "PRSC40");
//        data.put("Rahim yar Khan", "PRRD41");
//        data.put("Rahim yar Khan", "PRSA42");
//        data.put("Rahim yar Khan", "PRLP43");
//        data.put("Rahim yar Khan", "PRKC44");
//        data.put("Rahim yar Khan", "PRRR45");
//        data.put("Rahim yar Khan", "PRK746");
//        data.put("Rahim yar Khan", "PRLP47");
//        data.put("Rahim yar Khan", "PRS148");
//        data.put("Rahim yar Khan", "PRRK49");
//        data.put("Rahim yar Khan", "PRRA50");
//        data.put("Rahim yar Khan", "PRK751");
//        data.put("Rahim yar Khan", "PRKL52");
//        data.put("Rahim yar Khan", "PRKM53");
//        data.put("Rahim yar Khan", "PRRS54");
//        data.put("Rahim yar Khan", "PRSC55");
//        data.put("Rahim yar Khan", "PRKN56");
//        data.put("Rahim yar Khan", "PRKC57");
//        data.put("Rahim yar Khan", "PRK758");
//        data.put("Rahim yar Khan", "PRLZ59");
//        data.put("Rahim yar Khan", "PRKS60");
//        data.put("Rahim yar Khan", "PRLS61");
//        data.put("Rahim yar Khan", "PRLP62");
//        data.put("Rahim yar Khan", "PRRA63");
//        data.put("Rahim yar Khan", "PRLG64");
//        data.put("Rahim yar Khan", "PRRT65");
//        data.put("Rahim yar Khan", "PRRS66");
//        data.put("Rahim yar Khan", "PRKM67");
//        data.put("Rahim yar Khan", "PRKS68");
//        data.put("Rahim yar Khan", "PRRC69");
//        data.put("Rahim yar Khan", "PRRS70");
//        data.put("Rahim yar Khan", "PRLK71");
//        data.put("Rahim yar Khan", "PRRC72");
//        data.put("Rahim yar Khan", "PRKQ73");
//        data.put("Rahim yar Khan", "PRKC74");
//        data.put("Rahim yar Khan", "PRS275");
//        data.put("Rahim yar Khan", "PRLA76");
//        data.put("Rahim yar Khan", "PRR277");
//        data.put("Rahim yar Khan", "PRRC78");
//        data.put("Rahim yar Khan", "PRLd79");
//        data.put("Rahim yar Khan", "PRR380");
//        data.put("Rahim yar Khan", "PRRA81");
//        data.put("Rahim yar Khan", "PRRC82");
//        data.put("Rahim yar Khan", "PRRC83");
//        data.put("Rahim yar Khan", "PRRK84");
//        data.put("Rahim yar Khan", "PRKM85");
//        data.put("Rahim yar Khan", "PRK786");
//        data.put("Rahim yar Khan", "PRRK87");
//        data.put("Rahim yar Khan", "PRS188");
//        data.put("Rahim yar Khan", "PRRS89");
//        data.put("Rahim yar Khan", "PRRC90");
//        data.put("Rahim yar Khan", "PRRA91");
//        data.put("Rahim yar Khan", "PRS192");
//        data.put("Rahim yar Khan", "PRRC93");
//        data.put("Rahim yar Khan", "PRKS94");
//        data.put("Rahim yar Khan", "PRRD95");
//        data.put("Rahim yar Khan", "PRSD96");
//        data.put("Rahim yar Khan", "PRKN97");
//        data.put("Rahim yar Khan", "PRRS98");
//        data.put("Rahim yar Khan", "PRKJ99");
//        data.put("Rahim yar Khan", "PRLc100");
//        data.put("Rahim yar Khan", "PRSB101");
//        data.put("Rahim yar Khan", "PRRB102");
//        data.put("Rahim yar Khan", "PRRA103");
//        data.put("Rahim yar Khan", "PRRM104");
//        data.put("Rahim yar Khan", "PRLS105");
//        data.put("Rahim yar Khan", "PRRK106");
//        data.put("Rahim yar Khan", "PRRM107");
//        data.put("Rahim yar Khan", "PRKB108");
//        data.put("Rahim yar Khan", "PRS1109");
//        data.put("Rahim yar Khan", "PRKM110");
//        data.put("Rahim yar Khan", "PRKZ111");
//        data.put("Rahim yar Khan", "PRKJ112");
//        data.put("Rahim yar Khan", "PRKS113");
//        data.put("Rahim yar Khan", "PRRH114");
//        data.put("Rahim yar Khan", "PRKJ115");
//        data.put("Rahim yar Khan", "PRSG116");
//        data.put("Rahim yar Khan", "PRSJ117");
//        data.put("Rahim yar Khan", "PRKS118");
//        data.put("Rahim yar Khan", "PRS2119");
//        data.put("Rahim yar Khan", "PRLA120");
//        data.put("Rahim yar Khan", "PRLT121");
//        data.put("Rahim yar Khan", "PRRA122");
//        data.put("Rahim yar Khan", "PRSA123");
//        data.put("Rahim yar Khan", "PRK7124");
//        data.put("Rahim yar Khan", "PRSA125");
//        data.put("Rahim yar Khan", "PRKC126");
//        data.put("Rahim yar Khan", "PRRB127");
//        data.put("Rahim yar Khan", "PRRC128");
//        data.put("Rahim yar Khan", "PRKJ129");
//        data.put("Rahim yar Khan", "PRSR130");
//        data.put("Rahim yar Khan", "PRSK131");
//        data.put("Rahim yar Khan", "PRRC132");
//        data.put("Rahim yar Khan", "PRK7133");
//        data.put("Rahim yar Khan", "PRS2134");
//        data.put("Rahim yar Khan", "PRRM135");
//        data.put("Rahim yar Khan", "PRRA136");
//        data.put("Rahim yar Khan", "PRKJ137");
//        data.put("Rahim yar Khan", "PRSC138");
//        data.put("Rahim yar Khan", "PRRM139");
//        data.put("Rahim yar Khan", "PRSB140");
//        data.put("Rahim yar Khan", "PRKN141");
//        data.put("Rahim yar Khan", "PRSS142");
//        data.put("Rahim yar Khan", "PRKA143");
//        data.put("Rahim yar Khan", "PRKJ144");
//        data.put("Rahim yar Khan", "PRSA145");
//        data.put("Rahim yar Khan", "PRKN146");
//        data.put("Rahim yar Khan", "PRKM147");
//        data.put("Rahim yar Khan", "PRKL148");
//        data.put("Rahim yar Khan", "PRKZ149");
//        data.put("Rahim yar Khan", "PRKM150");
//
//
//        ///////////////////////////// Rahim Ray Khan Uncoverd///////////////////////
//
//
//        data.put("Rahim yar Khan", "PRRM151");
//        data.put("Rahim yar Khan", "PRLN152");
//        data.put("Rahim yar Khan", "PRSC153");
//        data.put("Rahim yar Khan", "PRKN154");
//        data.put("Rahim yar Khan", "PRSM155");
//        data.put("Rahim yar Khan", "PRRB156");
//        data.put("Rahim yar Khan", "PRKG157");
//        data.put("Rahim yar Khan", "PRSK158");
//        data.put("Rahim yar Khan", "PRRC159");
//        data.put("Rahim yar Khan", "PRLA160");
//        data.put("Rahim yar Khan", "PRRC161");
//        data.put("Rahim yar Khan", "PRSC162");
//        data.put("Rahim yar Khan", "PRSM163");
//        data.put("Rahim yar Khan", "PRLc164");
//        data.put("Rahim yar Khan", "PRSN165");
//        data.put("Rahim yar Khan", "PRLJ166");
//        data.put("Rahim yar Khan", "PRKQ167");
//        data.put("Rahim yar Khan", "PRKZ168");
//        data.put("Rahim yar Khan", "PRLc169");
//        data.put("Rahim yar Khan", "PRSM170");
//        data.put("Rahim yar Khan", "PRRS171");
//        data.put("Rahim yar Khan", "PRKD172");
//        data.put("Rahim yar Khan", "PRSC173");
//        data.put("Rahim yar Khan", "PRLc174");
//        data.put("Rahim yar Khan", "PRRC175");
//        data.put("Rahim yar Khan", "PRKZ176");
//        data.put("Rahim yar Khan", "PRSA177");
//        data.put("Rahim yar Khan", "PRKN178");
//        data.put("Rahim yar Khan", "PRSK179");
//        data.put("Rahim yar Khan", "PRRC180");
//        data.put("Rahim yar Khan", "PRSN181");
//        data.put("Rahim yar Khan", "PRLc182");
//        data.put("Rahim yar Khan", "PRKN183");
//        data.put("Rahim yar Khan", "PRSC184");
//        data.put("Rahim yar Khan", "PRRC185");
//        data.put("Rahim yar Khan", "PRSB186");
//        data.put("Rahim yar Khan", "PRRC187");
//        data.put("Rahim yar Khan", "PRSD188");
//        data.put("Rahim yar Khan", "PRSC189");
//        data.put("Rahim yar Khan", "PRLA190");
//        data.put("Rahim yar Khan", "PRKN191");
//        data.put("Rahim yar Khan", "PRRK192");
//        data.put("Rahim yar Khan", "PRSM193");
//        data.put("Rahim yar Khan", "PRRB194");
//        data.put("Rahim yar Khan", "PRSK195");
//        data.put("Rahim yar Khan", "PRRS196");
//        data.put("Rahim yar Khan", "PRLA197");
//        data.put("Rahim yar Khan", "PRLd198");
//        data.put("Rahim yar Khan", "PRSD199");
//        data.put("Rahim yar Khan", "PRSJ200");
//        data.put("Rahim yar Khan", "PRSA201");
//        data.put("Rahim yar Khan", "PRSM202");
//        data.put("Rahim yar Khan", "PRKN203");
//        data.put("Rahim yar Khan", "PRLJ204");
//        data.put("Rahim yar Khan", "PRKN205");
//        data.put("Rahim yar Khan", "PRKI206");
//        data.put("Rahim yar Khan", "PRSD207");
//        data.put("Rahim yar Khan", "PRR3208");
//        data.put("Rahim yar Khan", "PRLD209");
//        data.put("Rahim yar Khan", "PRLG210");
//        data.put("Rahim yar Khan", "PRRD211");
//        data.put("Rahim yar Khan", "PRLc212");
//        data.put("Rahim yar Khan", "PRSK213");
//        data.put("Rahim yar Khan", "PRSG214");
//        data.put("Rahim yar Khan", "PRLd215");
//        data.put("Rahim yar Khan", "PRKG216");
//        data.put("Rahim yar Khan", "PRK7217");
//        data.put("Rahim yar Khan", "PRRA218");
//        data.put("Rahim yar Khan", "PRLJ219");
//        data.put("Rahim yar Khan", "PRS1220");
//        data.put("Rahim yar Khan", "PRK7221");
//        data.put("Rahim yar Khan", "PRLc222");
//        data.put("Rahim yar Khan", "PRRA223");
//        data.put("Rahim yar Khan", "PRK7224");
//        data.put("Rahim yar Khan", "PRRK225");
//        data.put("Rahim yar Khan", "PRRR226");
//        data.put("Rahim yar Khan", "PRSK227");
//        data.put("Rahim yar Khan", "PRLc228");
//        data.put("Rahim yar Khan", "PRLD229");
//        data.put("Rahim yar Khan", "PRRH230");
//        data.put("Rahim yar Khan", "PRSK231");
//        data.put("Rahim yar Khan", "PRS1232");
//        data.put("Rahim yar Khan", "PRRB233");
//        data.put("Rahim yar Khan", "PRLM234");
//        data.put("Rahim yar Khan", "PRSB235");
//        data.put("Rahim yar Khan", "PRRB236");
//        data.put("Rahim yar Khan", "PRRR237");
//        data.put("Rahim yar Khan", "PRLC238");
//        data.put("Rahim yar Khan", "PRRS239");
//        data.put("Rahim yar Khan", "PRLG240");
//        data.put("Rahim yar Khan", "PRSD241");
//        data.put("Rahim yar Khan", "PRKG242");
//        data.put("Rahim yar Khan", "PRKS243");
//        data.put("Rahim yar Khan", "PRKG244");
//        data.put("Rahim yar Khan", "PRKS245");
//        data.put("Rahim yar Khan", "PRKG246");
//        data.put("Rahim yar Khan", "PRSD247");
//        data.put("Rahim yar Khan", "PRSA248");
//        data.put("Rahim yar Khan", "PRSM249");
//        data.put("Rahim yar Khan", "PRRS250");
//
//
////////////////////////////////////////////////////////////////////////
//
//        //*************************************//  Uncoverd....
//
//
//        data.put("QambarShahdadkot", "SQSA151");
//        data.put("QambarShahdadkot", "SQST152");
//        data.put("QambarShahdadkot", "SQMM153");
//        data.put("QambarShahdadkot", "SQNM154");
//        data.put("QambarShahdadkot", "SQNN155");
//        data.put("QambarShahdadkot", "SQQB156");
//        data.put("QambarShahdadkot", "SQQQ157");
//        data.put("QambarShahdadkot", "SQQJ158");
//        data.put("QambarShahdadkot", "SQSA159");
//        data.put("QambarShahdadkot", "SQQB160");
//        data.put("QambarShahdadkot", "SQQB161");
//        data.put("QambarShahdadkot", "SQWW162");
//        data.put("QambarShahdadkot", "SQWL163");
//        data.put("QambarShahdadkot", "SQQB164");
//        data.put("QambarShahdadkot", "SQMK165");
//        data.put("QambarShahdadkot", "SQMB166");
//        data.put("QambarShahdadkot", "SQQD167");
//        data.put("QambarShahdadkot", "SQQB168");
//        data.put("QambarShahdadkot", "SQWL169");
//        data.put("QambarShahdadkot", "SQQK170");
//        data.put("QambarShahdadkot", "SQSJ171");
//        data.put("QambarShahdadkot", "SQMK172");
//        data.put("QambarShahdadkot", "SQST173");
//        data.put("QambarShahdadkot", "SQSA174");
//        data.put("QambarShahdadkot", "SQQB175");
//        data.put("QambarShahdadkot", "SQWA176");
//        data.put("QambarShahdadkot", "SQQJ177");
//        data.put("QambarShahdadkot", "SQWM178");
//        data.put("QambarShahdadkot", "SQSM179");
//        data.put("QambarShahdadkot", "SQSD180");
//        data.put("QambarShahdadkot", "SQQJ181");
//        data.put("QambarShahdadkot", "SQSJ182");
//        data.put("QambarShahdadkot", "SQQR183");
//        data.put("QambarShahdadkot", "SQQB184");
//        data.put("QambarShahdadkot", "SQQQ185");
//        data.put("QambarShahdadkot", "SQWA186");
//        data.put("QambarShahdadkot", "SQQJ187");
//        data.put("QambarShahdadkot", "SQSS188");
//        data.put("QambarShahdadkot", "SQQB189");
//        data.put("QambarShahdadkot", "SQQQ190");
//        data.put("QambarShahdadkot", "SQSJ191");
//        data.put("QambarShahdadkot", "SQMK192");
//        data.put("QambarShahdadkot", "SQSS193");
//        data.put("QambarShahdadkot", "SQSS194");
//        data.put("QambarShahdadkot", "SQQK195");
//        data.put("QambarShahdadkot", "SQSJ196");
//        data.put("QambarShahdadkot", "SQSA197");
//        data.put("QambarShahdadkot", "SQQG198");
//        data.put("QambarShahdadkot", "SQSJ199");
//        data.put("QambarShahdadkot", "SQND200");
//        data.put("QambarShahdadkot", "SQWM201");
//        data.put("QambarShahdadkot", "SQSD202");
//        data.put("QambarShahdadkot", "SQQB203");
//        data.put("QambarShahdadkot", "SQQJ204");
//        data.put("QambarShahdadkot", "SQND205");
//        data.put("QambarShahdadkot", "SQNL206");
//        data.put("QambarShahdadkot", "SQQB207");
//        data.put("QambarShahdadkot", "SQQH208");
//        data.put("QambarShahdadkot", "SQSA209");
//        data.put("QambarShahdadkot", "SQNM210");
//        data.put("QambarShahdadkot", "SQQG211");
//        data.put("QambarShahdadkot", "SQWW212");
//        data.put("QambarShahdadkot", "SQSJ213");
//        data.put("QambarShahdadkot", "SQST214");
//        data.put("QambarShahdadkot", "SQWA215");
//        data.put("QambarShahdadkot", "SQQG216");
//        data.put("QambarShahdadkot", "SQSD217");
//        data.put("QambarShahdadkot", "SQNL218");
//        data.put("QambarShahdadkot", "SQSJ219");
//        data.put("QambarShahdadkot", "SQQH220");
//        data.put("QambarShahdadkot", "SQQJ221");
//        data.put("QambarShahdadkot", "SQQG222");
//        data.put("QambarShahdadkot", "SQWW223");
//        data.put("QambarShahdadkot", "SQSS224");
//        data.put("QambarShahdadkot", "SQWL225");
//        data.put("QambarShahdadkot", "SQWW226");
//        data.put("QambarShahdadkot", "SQQH227");
//        data.put("QambarShahdadkot", "SQSA228");
//        data.put("QambarShahdadkot", "SQQB229");
//        data.put("QambarShahdadkot", "SQQB230");
//        data.put("QambarShahdadkot", "SQQB231");
//        data.put("QambarShahdadkot", "SQNL232");
//        data.put("QambarShahdadkot", "SQSM233");
//        data.put("QambarShahdadkot", "SQQQ234");
//        data.put("QambarShahdadkot", "SQWM235");
//        data.put("QambarShahdadkot", "SQWG236");
//        data.put("QambarShahdadkot", "SQSS237");
//        data.put("QambarShahdadkot", "SQWA238");
//        data.put("QambarShahdadkot", "SQSJ239");
//        data.put("QambarShahdadkot", "SQSA240");
//        data.put("QambarShahdadkot", "SQQK241");
//        data.put("QambarShahdadkot", "SQQG242");
//        data.put("QambarShahdadkot", "SQQB243");
//        data.put("QambarShahdadkot", "SQQJ244");
//        data.put("QambarShahdadkot", "SQQR245");
//        data.put("QambarShahdadkot", "SQWA246");
//        data.put("QambarShahdadkot", "SQQJ247");
//        data.put("QambarShahdadkot", "SQQD248");
//        data.put("QambarShahdadkot", "SQSA249");
//        data.put("QambarShahdadkot", "SQMB250");
//
//
//        //*************************************//  Coverd....
//
//        data.put("QambarShahdadkot", "SQSJ1");
//        data.put("QambarShahdadkot", "SQQQ2");
//        data.put("QambarShahdadkot", "SQQQ3");
//        data.put("QambarShahdadkot", "SQNL4");
//        data.put("QambarShahdadkot", "SQSS5");
//        data.put("QambarShahdadkot", "SQSS6");
//        data.put("QambarShahdadkot", "SQNN7");
//        data.put("QambarShahdadkot", "SQSS8");
//        data.put("QambarShahdadkot", "SQNM9");
//        data.put("QambarShahdadkot", "SQMB10");
//        data.put("QambarShahdadkot", "SQND11");
//        data.put("QambarShahdadkot", "SQMM12");
//        data.put("QambarShahdadkot", "SQNN13");
//        data.put("QambarShahdadkot", "SQQB14");
//        data.put("QambarShahdadkot", "SQQQ15");
//        data.put("QambarShahdadkot", "SQSJ16");
//        data.put("QambarShahdadkot", "SQQQ17");
//        data.put("QambarShahdadkot", "SQSS18");
//        data.put("QambarShahdadkot", "SQMM19");
//        data.put("QambarShahdadkot", "SQNM20");
//        data.put("QambarShahdadkot", "SQSS21");
//        data.put("QambarShahdadkot", "SQSS22");
//        data.put("QambarShahdadkot", "SQQR23");
//        data.put("QambarShahdadkot", "SQQQ24");
//        data.put("QambarShahdadkot", "SQMM25");
//        data.put("QambarShahdadkot", "SQSJ26");
//        data.put("QambarShahdadkot", "SQNL27");
//        data.put("QambarShahdadkot", "SQQK28");
//        data.put("QambarShahdadkot", "SQQK29");
//        data.put("QambarShahdadkot", "SQSS30");
//        data.put("QambarShahdadkot", "SQMK31");
//        data.put("QambarShahdadkot", "SQQR32");
//        data.put("QambarShahdadkot", "SQNN33");
//        data.put("QambarShahdadkot", "SQSA34");
//        data.put("QambarShahdadkot", "SQQJ35");
//        data.put("QambarShahdadkot", "SQMB36");
//        data.put("QambarShahdadkot", "SQSA37");
//        data.put("QambarShahdadkot", "SQQR38");
//        data.put("QambarShahdadkot", "SQMB39");
//        data.put("QambarShahdadkot", "SQSS40");
//        data.put("QambarShahdadkot", "SQSS41");
//        data.put("QambarShahdadkot", "SQSS42");
//        data.put("QambarShahdadkot", "SQSS43");
//        data.put("QambarShahdadkot", "SQNN44");
//        data.put("QambarShahdadkot", "SQQQ45");
//        data.put("QambarShahdadkot", "SQNM46");
//        data.put("QambarShahdadkot", "SQQR47");
//        data.put("QambarShahdadkot", "SQSJ48");
//        data.put("QambarShahdadkot", "SQMM49");
//        data.put("QambarShahdadkot", "SQSS50");
//        data.put("QambarShahdadkot", "SQQQ51");
//        data.put("QambarShahdadkot", "SQMB52");
//        data.put("QambarShahdadkot", "SQMB53");
//        data.put("QambarShahdadkot", "SQQB54");
//        data.put("QambarShahdadkot", "SQQB55");
//        data.put("QambarShahdadkot", "SQMK56");
//        data.put("QambarShahdadkot", "SQQK57");
//        data.put("QambarShahdadkot", "SQSA58");
//        data.put("QambarShahdadkot", "SQQQ59");
//        data.put("QambarShahdadkot", "SQQR60");
//        data.put("QambarShahdadkot", "SQQJ61");
//        data.put("QambarShahdadkot", "SQSS62");
//        data.put("QambarShahdadkot", "SQSJ63");
//        data.put("QambarShahdadkot", "SQNL64");
//        data.put("QambarShahdadkot", "SQQQ65");
//        data.put("QambarShahdadkot", "SQSS66");
//        data.put("QambarShahdadkot", "SQQR67");
//        data.put("QambarShahdadkot", "SQQB68");
//        data.put("QambarShahdadkot", "SQSA69");
//        data.put("QambarShahdadkot", "SQSS70");
//        data.put("QambarShahdadkot", "SQMB71");
//        data.put("QambarShahdadkot", "SQMB72");
//        data.put("QambarShahdadkot", "SQSS73");
//        data.put("QambarShahdadkot", "SQQB74");
//        data.put("QambarShahdadkot", "SQNM75");
//        data.put("QambarShahdadkot", "SQQR76");
//        data.put("QambarShahdadkot", "SQNN77");
//        data.put("QambarShahdadkot", "SQMM78");
//        data.put("QambarShahdadkot", "SQNN79");
//        data.put("QambarShahdadkot", "SQSS80");
//        data.put("QambarShahdadkot", "SQSA81");
//        data.put("QambarShahdadkot", "SQMM82");
//        data.put("QambarShahdadkot", "SQQK83");
//        data.put("QambarShahdadkot", "SQNN84");
//        data.put("QambarShahdadkot", "SQSS85");
//        data.put("QambarShahdadkot", "SQSS86");
//        data.put("QambarShahdadkot", "SQSS87");
//        data.put("QambarShahdadkot", "SQNL88");
//        data.put("QambarShahdadkot", "SQMB89");
//        data.put("QambarShahdadkot", "SQNL90");
//        data.put("QambarShahdadkot", "SQSS91");
//        data.put("QambarShahdadkot", "SQMM92");
//        data.put("QambarShahdadkot", "SQMK93");
//        data.put("QambarShahdadkot", "SQNL94");
//        data.put("QambarShahdadkot", "SQMM95");
//        data.put("QambarShahdadkot", "SQNN96");
//        data.put("QambarShahdadkot", "SQSA97");
//        data.put("QambarShahdadkot", "SQNM98");
//        data.put("QambarShahdadkot", "SQNL99");
//        data.put("QambarShahdadkot", "SQMM100");
//        data.put("QambarShahdadkot", "SQQR101");
//        data.put("QambarShahdadkot", "SQSA102");
//        data.put("QambarShahdadkot", "SQSS103");
//        data.put("QambarShahdadkot", "SQNN104");
//        data.put("QambarShahdadkot", "SQQK105");
//        data.put("QambarShahdadkot", "SQNM106");
//        data.put("QambarShahdadkot", "SQMM107");
//        data.put("QambarShahdadkot", "SQMB108");
//        data.put("QambarShahdadkot", "SQQK109");
//        data.put("QambarShahdadkot", "SQMM110");
//        data.put("QambarShahdadkot", "SQNM111");
//        data.put("QambarShahdadkot", "SQQD112");
//        data.put("QambarShahdadkot", "SQQB113");
//        data.put("QambarShahdadkot", "SQNM114");
//        data.put("QambarShahdadkot", "SQQK115");
//        data.put("QambarShahdadkot", "SQSS116");
//        data.put("QambarShahdadkot", "SQSS117");
//        data.put("QambarShahdadkot", "SQSS118");
//        data.put("QambarShahdadkot", "SQND119");
//        data.put("QambarShahdadkot", "SQSS120");
//        data.put("QambarShahdadkot", "SQSA121");
//        data.put("QambarShahdadkot", "SQND122");
//        data.put("QambarShahdadkot", "SQQB123");
//        data.put("QambarShahdadkot", "SQSJ124");
//        data.put("QambarShahdadkot", "SQQB125");
//        data.put("QambarShahdadkot", "SQMM126");
//        data.put("QambarShahdadkot", "SQQG127");
//        data.put("QambarShahdadkot", "SQSS128");
//        data.put("QambarShahdadkot", "SQMB129");
//        data.put("QambarShahdadkot", "SQSA130");
//        data.put("QambarShahdadkot", "SQMK131");
//        data.put("QambarShahdadkot", "SQSJ132");
//        data.put("QambarShahdadkot", "SQSA133");
//        data.put("QambarShahdadkot", "SQSA134");
//        data.put("QambarShahdadkot", "SQSS135");
//        data.put("QambarShahdadkot", "SQNN136");
//        data.put("QambarShahdadkot", "SQSA137");
//        data.put("QambarShahdadkot", "SQNM138");
//        data.put("QambarShahdadkot", "SQMM139");
//        data.put("QambarShahdadkot", "SQNL140");
//        data.put("QambarShahdadkot", "SQSS141");
//        data.put("QambarShahdadkot", "SQSS142");
//        data.put("QambarShahdadkot", "SQSS143");
//        data.put("QambarShahdadkot", "SQSJ144");
//        data.put("QambarShahdadkot", "SQSJ145");
//        data.put("QambarShahdadkot", "SQMB146");
//        data.put("QambarShahdadkot", "SQMB147");
//        data.put("QambarShahdadkot", "SQSS148");
//        data.put("QambarShahdadkot", "SQSS149");
//        data.put("QambarShahdadkot", "SQNN150");
//
//////////////////////////////////////////////////////////// NaserAbad Jafar Abad//////////////////////////
//
//
//        data.put("JaffarabadNaseerabad", "BJJC1");
//        data.put("JaffarabadNaseerabad", "BJTA2");
//        data.put("JaffarabadNaseerabad", "BJGS3");
//        data.put("JaffarabadNaseerabad", "BJTM4");
//        data.put("JaffarabadNaseerabad", "BJJR5");
//        data.put("JaffarabadNaseerabad", "BJDT6");
//        data.put("JaffarabadNaseerabad", "BJTA7");
//        data.put("JaffarabadNaseerabad", "BJJU8");
//        data.put("JaffarabadNaseerabad", "BJDM9");
//        data.put("JaffarabadNaseerabad", "BJDA10");
//        data.put("JaffarabadNaseerabad", "BJGS11");
//        data.put("JaffarabadNaseerabad", "BJTA12");
//        data.put("JaffarabadNaseerabad", "BJGG13");
//        data.put("JaffarabadNaseerabad", "BJTM14");
//        data.put("JaffarabadNaseerabad", "BJGS15");
//        data.put("JaffarabadNaseerabad", "BJDT16");
//        data.put("JaffarabadNaseerabad", "BJGG17");
//        data.put("JaffarabadNaseerabad", "BJTA18");
//        data.put("JaffarabadNaseerabad", "BJTM19");
//        data.put("JaffarabadNaseerabad", "BJGG20");
//        data.put("JaffarabadNaseerabad", "BJTF21");
//        data.put("JaffarabadNaseerabad", "BJTA22");
//        data.put("JaffarabadNaseerabad", "BJTM23");
//        data.put("JaffarabadNaseerabad", "BJTM24");
//        data.put("JaffarabadNaseerabad", "BJTA25");
//        data.put("JaffarabadNaseerabad", "BJJB26");
//        data.put("JaffarabadNaseerabad", "BJTK27");
//        data.put("JaffarabadNaseerabad", "BJTF28");
//        data.put("JaffarabadNaseerabad", "BJJC29");
//        data.put("JaffarabadNaseerabad", "BJTK30");
//        data.put("JaffarabadNaseerabad", "BJTF31");
//        data.put("JaffarabadNaseerabad", "BJTM32");
//        data.put("JaffarabadNaseerabad", "BJDT33");
//        data.put("JaffarabadNaseerabad", "BJDT34");
//        data.put("JaffarabadNaseerabad", "BJTK35");
//        data.put("JaffarabadNaseerabad", "BJGS36");
//        data.put("JaffarabadNaseerabad", "BJJH37");
//        data.put("JaffarabadNaseerabad", "BJJC38");
//        data.put("JaffarabadNaseerabad", "BJJU39");
//        data.put("JaffarabadNaseerabad", "BJTK40");
//        data.put("JaffarabadNaseerabad", "BJTK41");
//        data.put("JaffarabadNaseerabad", "BJDT42");
//        data.put("JaffarabadNaseerabad", "BJJN43");
//        data.put("JaffarabadNaseerabad", "BJGS44");
//        data.put("JaffarabadNaseerabad", "BJGG45");
//        data.put("JaffarabadNaseerabad", "BJGS46");
//        data.put("JaffarabadNaseerabad", "BJJU47");
//        data.put("JaffarabadNaseerabad", "BJTK48");
//        data.put("JaffarabadNaseerabad", "BJUA49");
//        data.put("JaffarabadNaseerabad", "BJJB50");
//        data.put("JaffarabadNaseerabad", "BJTA51");
//        data.put("JaffarabadNaseerabad", "BJTF52");
//        data.put("JaffarabadNaseerabad", "BJTA53");
//        data.put("JaffarabadNaseerabad", "BJDT54");
//        data.put("JaffarabadNaseerabad", "BJUU55");
//        data.put("JaffarabadNaseerabad", "BJTK56");
//        data.put("JaffarabadNaseerabad", "BJTA57");
//        data.put("JaffarabadNaseerabad", "BJTA58");
//        data.put("JaffarabadNaseerabad", "BJGS59");
//        data.put("JaffarabadNaseerabad", "BJJU60");
//        data.put("JaffarabadNaseerabad", "BJJU61");
//        data.put("JaffarabadNaseerabad", "BJTA62");
//        data.put("JaffarabadNaseerabad", "BJJB63");
//        data.put("JaffarabadNaseerabad", "BJTK64");
//        data.put("JaffarabadNaseerabad", "BJGG65");
//        data.put("JaffarabadNaseerabad", "BJUU66");
//        data.put("JaffarabadNaseerabad", "BJTK67");
//        data.put("JaffarabadNaseerabad", "BJTA68");
//        data.put("JaffarabadNaseerabad", "BJJR69");
//        data.put("JaffarabadNaseerabad", "BJDB70");
//        data.put("JaffarabadNaseerabad", "BJUK71");
//        data.put("JaffarabadNaseerabad", "BJDT72");
//        data.put("JaffarabadNaseerabad", "BJDT73");
//        data.put("JaffarabadNaseerabad", "BJDA74");
//        data.put("JaffarabadNaseerabad", "BJTA75");
//        data.put("JaffarabadNaseerabad", "BJJC76");
//        data.put("JaffarabadNaseerabad", "BJJS77");
//        data.put("JaffarabadNaseerabad", "BJDB78");
//        data.put("JaffarabadNaseerabad", "BJGG79");
//        data.put("JaffarabadNaseerabad", "BJJU80");
//        data.put("JaffarabadNaseerabad", "BJDT81");
//        data.put("JaffarabadNaseerabad", "BJTA82");
//        data.put("JaffarabadNaseerabad", "BJUU83");
//        data.put("JaffarabadNaseerabad", "BJTK84");
//        data.put("JaffarabadNaseerabad", "BJTF85");
//        data.put("JaffarabadNaseerabad", "BJUU86");
//        data.put("JaffarabadNaseerabad", "BJTA87");
//        data.put("JaffarabadNaseerabad", "BJTA88");
//        data.put("JaffarabadNaseerabad", "BJTM89");
//        data.put("JaffarabadNaseerabad", "BJUU90");
//        data.put("JaffarabadNaseerabad", "BJDB91");
//        data.put("JaffarabadNaseerabad", "BJGG92");
//        data.put("JaffarabadNaseerabad", "BJUU93");
//        data.put("JaffarabadNaseerabad", "BJTM94");
//        data.put("JaffarabadNaseerabad", "BJTA95");
//        data.put("JaffarabadNaseerabad", "BJJR96");
//        data.put("JaffarabadNaseerabad", "BJDT97");
//        data.put("JaffarabadNaseerabad", "BJTM98");
//        data.put("JaffarabadNaseerabad", "BJJU99");
//        data.put("JaffarabadNaseerabad", "BJTF100");
//        data.put("JaffarabadNaseerabad", "BJTK101");
//        data.put("JaffarabadNaseerabad", "BJJU102");
//        data.put("JaffarabadNaseerabad", "BJDT103");
//        data.put("JaffarabadNaseerabad", "BJDM104");
//        data.put("JaffarabadNaseerabad", "BJJC105");
//        data.put("JaffarabadNaseerabad", "BJTF106");
//        data.put("JaffarabadNaseerabad", "BJJC107");
//        data.put("JaffarabadNaseerabad", "BJJU108");
//        data.put("JaffarabadNaseerabad", "BJTK109");
//        data.put("JaffarabadNaseerabad", "BJDT110");
//        data.put("JaffarabadNaseerabad", "BJJU111");
//        data.put("JaffarabadNaseerabad", "BJTA112");
//        data.put("JaffarabadNaseerabad", "BJDT113");
//        data.put("JaffarabadNaseerabad", "BJUU114");
//        data.put("JaffarabadNaseerabad", "BJGG115");
//        data.put("JaffarabadNaseerabad", "BJTA116");
//        data.put("JaffarabadNaseerabad", "BJDT117");
//        data.put("JaffarabadNaseerabad", "BJTA118");
//        data.put("JaffarabadNaseerabad", "BJTK119");
//        data.put("JaffarabadNaseerabad", "BJJU120");
//        data.put("JaffarabadNaseerabad", "BJUA121");
//        data.put("JaffarabadNaseerabad", "BJJU122");
//        data.put("JaffarabadNaseerabad", "BJJR123");
//        data.put("JaffarabadNaseerabad", "BJTA124");
//        data.put("JaffarabadNaseerabad", "BJTK125");
//        data.put("JaffarabadNaseerabad", "BJGG126");
//        data.put("JaffarabadNaseerabad", "BJUU127");
//        data.put("JaffarabadNaseerabad", "BJGG128");
//        data.put("JaffarabadNaseerabad", "BJDM129");
//        data.put("JaffarabadNaseerabad", "BJTA130");
//        data.put("JaffarabadNaseerabad", "BJJU131");
//        data.put("JaffarabadNaseerabad", "BJTK132");
//        data.put("JaffarabadNaseerabad", "BJTK133");
//        data.put("JaffarabadNaseerabad", "BJJU134");
//        data.put("JaffarabadNaseerabad", "BJDM135");
//        data.put("JaffarabadNaseerabad", "BJTA136");
//        data.put("JaffarabadNaseerabad", "BJUS137");
//        data.put("JaffarabadNaseerabad", "BJGS138");
//        data.put("JaffarabadNaseerabad", "BJJU139");
//        data.put("JaffarabadNaseerabad", "BJDM140");
//        data.put("JaffarabadNaseerabad", "BJDT141");
//        data.put("JaffarabadNaseerabad", "BJDT142");
//        data.put("JaffarabadNaseerabad", "BJTM143");
//        data.put("JaffarabadNaseerabad", "BJGG144");
//        data.put("JaffarabadNaseerabad", "BJTK145");
//        data.put("JaffarabadNaseerabad", "BJDT146");
//        data.put("JaffarabadNaseerabad", "BJTF147");
//        data.put("JaffarabadNaseerabad", "BJDB148");
//        data.put("JaffarabadNaseerabad", "BJUU149");
//        data.put("JaffarabadNaseerabad", "BJUA150");
////////////////////////////// Jafarabad Uncoverd////////////
//
//
//        data.put("JaffarabadNaseerabad", "BNDS151");
//        data.put("JaffarabadNaseerabad", "BNDS152");
//        data.put("JaffarabadNaseerabad", "BNDS153");
//        data.put("JaffarabadNaseerabad", "BNDS154");
//        data.put("JaffarabadNaseerabad", "BNDS155");
//        data.put("JaffarabadNaseerabad", "BNDS156");
//        data.put("JaffarabadNaseerabad", "BNDS157");
//        data.put("JaffarabadNaseerabad", "BNDS158");
//        data.put("JaffarabadNaseerabad", "BNDS159");
//        data.put("JaffarabadNaseerabad", "BNDS160");
//        data.put("JaffarabadNaseerabad", "BNDS161");
//        data.put("JaffarabadNaseerabad", "BNDJ162");
//        data.put("JaffarabadNaseerabad", "BNDJ163");
//        data.put("JaffarabadNaseerabad", "BNDJ164");
//        data.put("JaffarabadNaseerabad", "BNBB165");
//        data.put("JaffarabadNaseerabad", "BNBB166");
//        data.put("JaffarabadNaseerabad", "BNBK167");
//        data.put("JaffarabadNaseerabad", "BNBK168");
//        data.put("JaffarabadNaseerabad", "BNBK169");
//        data.put("JaffarabadNaseerabad", "BNBK170");
//        data.put("JaffarabadNaseerabad", "BNBK171");
//        data.put("JaffarabadNaseerabad", "BNBK172");
//        data.put("JaffarabadNaseerabad", "BNTW173");
//        data.put("JaffarabadNaseerabad", "BNTW174");
//        data.put("JaffarabadNaseerabad", "BNDQ175");
//        data.put("JaffarabadNaseerabad", "BNTJ176");
//        data.put("JaffarabadNaseerabad", "BNTJ177");
//        data.put("JaffarabadNaseerabad", "BNTJ178");
//        data.put("JaffarabadNaseerabad", "BNTA179");
//        data.put("JaffarabadNaseerabad", "BNTA180");
//        data.put("JaffarabadNaseerabad", "BNTA181");
//        data.put("JaffarabadNaseerabad", "BNTA182");
//        data.put("JaffarabadNaseerabad", "BJJH183");
//        data.put("JaffarabadNaseerabad", "BJJH184");
//        data.put("JaffarabadNaseerabad", "BJJR185");
//        data.put("JaffarabadNaseerabad", "BJJR186");
//        data.put("JaffarabadNaseerabad", "BJJS187");
//        data.put("JaffarabadNaseerabad", "BJJC188");
//        data.put("JaffarabadNaseerabad", "BJJC189");
//        data.put("JaffarabadNaseerabad", "BJJC190");
//        data.put("JaffarabadNaseerabad", "BJJC191");
//        data.put("JaffarabadNaseerabad", "BJJS192");
//        data.put("JaffarabadNaseerabad", "BJJS193");
//        data.put("JaffarabadNaseerabad", "BJJS194");
//        data.put("JaffarabadNaseerabad", "BJJS195");
//        data.put("JaffarabadNaseerabad", "BJJS196");
//        data.put("JaffarabadNaseerabad", "BJJS197");
//        data.put("JaffarabadNaseerabad", "BJJA198");
//        data.put("JaffarabadNaseerabad", "BJJA199");
//        data.put("JaffarabadNaseerabad", "BJJA200");
//        data.put("JaffarabadNaseerabad", "BJJA201");
//        data.put("JaffarabadNaseerabad", "BJJB202");
//        data.put("JaffarabadNaseerabad", "BJJB203");
//        data.put("JaffarabadNaseerabad", "BJJB204");
//        data.put("JaffarabadNaseerabad", "BJJB205");
//        data.put("JaffarabadNaseerabad", "BJJT206");
//        data.put("JaffarabadNaseerabad", "BJJT207");
//        data.put("JaffarabadNaseerabad", "BJJT208");
//        data.put("JaffarabadNaseerabad", "BJJT209");
//        data.put("JaffarabadNaseerabad", "BJJR210");
//        data.put("JaffarabadNaseerabad", "BJJR211");
//        data.put("JaffarabadNaseerabad", "BJJR212");
//        data.put("JaffarabadNaseerabad", "BJJY213");
//        data.put("JaffarabadNaseerabad", "BJJY214");
//        data.put("JaffarabadNaseerabad", "BJJY215");
//        data.put("JaffarabadNaseerabad", "BJJS216");
//        data.put("JaffarabadNaseerabad", "BJJS217");
//        data.put("JaffarabadNaseerabad", "BJJB218");
//        data.put("JaffarabadNaseerabad", "BJUA219");
//        data.put("JaffarabadNaseerabad", "BJUA220");
//        data.put("JaffarabadNaseerabad", "BJUB221");
//        data.put("JaffarabadNaseerabad", "BJUB222");
//        data.put("JaffarabadNaseerabad", "BJUB223");
//        data.put("JaffarabadNaseerabad", "BJUB224");
//        data.put("JaffarabadNaseerabad", "BJUF225");
//        data.put("JaffarabadNaseerabad", "BJUF226");
//        data.put("JaffarabadNaseerabad", "BJUF227");
//        data.put("JaffarabadNaseerabad", "BJUF228");
//        data.put("JaffarabadNaseerabad", "BJUF229");
//        data.put("JaffarabadNaseerabad", "BJUK230");
//        data.put("JaffarabadNaseerabad", "BJUK231");
//        data.put("JaffarabadNaseerabad", "BJUM232");
//        data.put("JaffarabadNaseerabad", "BJUM233");
//        data.put("JaffarabadNaseerabad", "BJUM234");
//        data.put("JaffarabadNaseerabad", "BJUM235");
//        data.put("JaffarabadNaseerabad", "BJUS236");
//        data.put("JaffarabadNaseerabad", "BJUS237");
//        data.put("JaffarabadNaseerabad", "BJUS238");
//        data.put("JaffarabadNaseerabad", "BJUS239");
//        data.put("JaffarabadNaseerabad", "BJUS240");
//        data.put("JaffarabadNaseerabad", "BJUS241");
//        data.put("JaffarabadNaseerabad", "BJUH242");
//        data.put("JaffarabadNaseerabad", "BJUH243");
//        data.put("JaffarabadNaseerabad", "BJUq244");
//        data.put("JaffarabadNaseerabad", "BJUH245");
//        data.put("JaffarabadNaseerabad", "BJUQ246");
//        data.put("JaffarabadNaseerabad", "BJUQ247");
//        data.put("JaffarabadNaseerabad", "BJUP248");
//        data.put("JaffarabadNaseerabad", "BJUP249");
//        data.put("JaffarabadNaseerabad", "BJUP250");
//
//
//////////////////////////////////////////// Muzfargarh/////////////////////////
//
//
//        data.put("Muzfargarh", "PMKH1");
//        data.put("Muzfargarh", "PMJJ2");
//        data.put("Muzfargarh", "PMJK3");
//        data.put("Muzfargarh", "PMKW4");
//        data.put("Muzfargarh", "PMMN5");
//        data.put("Muzfargarh", "PMMC6");
//        data.put("Muzfargarh", "PMKD7");
//        data.put("Muzfargarh", "PMKB8");
//        data.put("Muzfargarh", "PMMN9");
//        data.put("Muzfargarh", "PMKE10");
//        data.put("Muzfargarh", "PMAA11");
//        data.put("Muzfargarh", "PMKB12");
//        data.put("Muzfargarh", "PMMC13");
//        data.put("Muzfargarh", "PMJM14");
//        data.put("Muzfargarh", "PMAS15");
//        data.put("Muzfargarh", "PMAG16");
//        data.put("Muzfargarh", "PMAF17");
//        data.put("Muzfargarh", "PMMN18");
//        data.put("Muzfargarh", "PMAY19");
//        data.put("Muzfargarh", "PMKU20");
//        data.put("Muzfargarh", "PMJM21");
//        data.put("Muzfargarh", "PMKH22");
//        data.put("Muzfargarh", "PMMB23");
//        data.put("Muzfargarh", "PMMA24");
//        data.put("Muzfargarh", "PMAG25");
//        data.put("Muzfargarh", "PMMB26");
//        data.put("Muzfargarh", "PMKU27");
//        data.put("Muzfargarh", "PMMA28");
//        data.put("Muzfargarh", "PMMT29");
//        data.put("Muzfargarh", "PMMU30");
//        data.put("Muzfargarh", "PMML31");
//        data.put("Muzfargarh", "PMMG32");
//        data.put("Muzfargarh", "PMKD33");
//        data.put("Muzfargarh", "PMMT34");
//        data.put("Muzfargarh", "PMMR35");
//        data.put("Muzfargarh", "PMKE36");
//        data.put("Muzfargarh", "PMMA37");
//        data.put("Muzfargarh", "PMKD38");
//        data.put("Muzfargarh", "PMKH39");
//        data.put("Muzfargarh", "PMKB40");
//        data.put("Muzfargarh", "PMKM41");
//        data.put("Muzfargarh", "PMJS42");
//        data.put("Muzfargarh", "PMMR43");
//        data.put("Muzfargarh", "PMMT44");
//        data.put("Muzfargarh", "PMMT45");
//        data.put("Muzfargarh", "PMKM46");
//        data.put("Muzfargarh", "PMJS47");
//        data.put("Muzfargarh", "PMKM48");
//        data.put("Muzfargarh", "PMAY49");
//        data.put("Muzfargarh", "PMKU50");
//        data.put("Muzfargarh", "PMJJ51");
//        data.put("Muzfargarh", "PMMA52");
//        data.put("Muzfargarh", "PMKG53");
//        data.put("Muzfargarh", "PMKT54");
//        data.put("Muzfargarh", "PMMT55");
//        data.put("Muzfargarh", "PMMG56");
//        data.put("Muzfargarh", "PMMK57");
//        data.put("Muzfargarh", "PMKW58");
//        data.put("Muzfargarh", "PMMJ59");
//        data.put("Muzfargarh", "PMMU60");
//        data.put("Muzfargarh", "PMJV61");
//        data.put("Muzfargarh", "PMKE62");
//        data.put("Muzfargarh", "PMMM63");
//        data.put("Muzfargarh", "PMMB64");
//        data.put("Muzfargarh", "PMMB65");
//        data.put("Muzfargarh", "PMKU66");
//        data.put("Muzfargarh", "PMMW67");
//        data.put("Muzfargarh", "PMKP68");
//        data.put("Muzfargarh", "PMJS69");
//        data.put("Muzfargarh", "PMMM70");
//        data.put("Muzfargarh", "PMJS71");
//        data.put("Muzfargarh", "PMMU72");
//        data.put("Muzfargarh", "PMMG73");
//        data.put("Muzfargarh", "PMKC74");
//        data.put("Muzfargarh", "PMMN75");
//        data.put("Muzfargarh", "PMMA76");
//        data.put("Muzfargarh", "PMJB77");
//        data.put("Muzfargarh", "PMMK78");
//        data.put("Muzfargarh", "PMMN79");
//        data.put("Muzfargarh", "PMML80");
//        data.put("Muzfargarh", "PMJS81");
//        data.put("Muzfargarh", "PMMC82");
//        data.put("Muzfargarh", "PMMA83");
//        data.put("Muzfargarh", "PMMG84");
//        data.put("Muzfargarh", "PMMB85");
//        data.put("Muzfargarh", "PMKB86");
//        data.put("Muzfargarh", "PMKS87");
//        data.put("Muzfargarh", "PMAG88");
//        data.put("Muzfargarh", "PMMC89");
//        data.put("Muzfargarh", "PMJJ90");
//        data.put("Muzfargarh", "PMAA91");
//        data.put("Muzfargarh", "PMMA92");
//        data.put("Muzfargarh", "PMJB93");
//        data.put("Muzfargarh", "PMKM94");
//        data.put("Muzfargarh", "PMML95");
//        data.put("Muzfargarh", "PMMA96");
//        data.put("Muzfargarh", "PMJJ97");
//        data.put("Muzfargarh", "PMKP98");
//        data.put("Muzfargarh", "PMKB99");
//        data.put("Muzfargarh", "PMKS100");
//        data.put("Muzfargarh", "PMMC101");
//        data.put("Muzfargarh", "PMMN102");
//        data.put("Muzfargarh", "PMJJ103");
//        data.put("Muzfargarh", "PMAA104");
//        data.put("Muzfargarh", "PMJB105");
//        data.put("Muzfargarh", "PMMA106");
//        data.put("Muzfargarh", "PMMB107");
//        data.put("Muzfargarh", "PMJD108");
//        data.put("Muzfargarh", "PMKS109");
//        data.put("Muzfargarh", "PMKM110");
//        data.put("Muzfargarh", "PMKE111");
//        data.put("Muzfargarh", "PMK5112");
//        data.put("Muzfargarh", "PMKG113");
//        data.put("Muzfargarh", "PMK6114");
//        data.put("Muzfargarh", "PMKM115");
//        data.put("Muzfargarh", "PMJJ116");
//        data.put("Muzfargarh", "PMML117");
//        data.put("Muzfargarh", "PMKU118");
//        data.put("Muzfargarh", "PMAM119");
//        data.put("Muzfargarh", "PMKG120");
//        data.put("Muzfargarh", "PMMR121");
//        data.put("Muzfargarh", "PMJB122");
//        data.put("Muzfargarh", "PMAG123");
//        data.put("Muzfargarh", "PMAM124");
//        data.put("Muzfargarh", "PMMA125");
//        data.put("Muzfargarh", "PMMW126");
//        data.put("Muzfargarh", "PMJM127");
//        data.put("Muzfargarh", "PMMT128");
//        data.put("Muzfargarh", "PMML129");
//        data.put("Muzfargarh", "PMMT130");
//        data.put("Muzfargarh", "PMJB131");
//        data.put("Muzfargarh", "PMMA132");
//        data.put("Muzfargarh", "PMKM133");
//        data.put("Muzfargarh", "PMAG134");
//        data.put("Muzfargarh", "PMMC135");
//        data.put("Muzfargarh", "PMKS136");
//        data.put("Muzfargarh", "PMMC137");
//        data.put("Muzfargarh", "PMKM138");
//        data.put("Muzfargarh", "PMMR139");
//        data.put("Muzfargarh", "PMMB140");
//        data.put("Muzfargarh", "PMMC141");
//        data.put("Muzfargarh", "PMJM142");
//        data.put("Muzfargarh", "PMKD143");
//        data.put("Muzfargarh", "PMAB144");
//        data.put("Muzfargarh", "PMMC145");
//        data.put("Muzfargarh", "PMJJ146");
//        data.put("Muzfargarh", "PMMM147");
//        data.put("Muzfargarh", "PMJJ148");
//        data.put("Muzfargarh", "PMKD149");
//        data.put("Muzfargarh", "PMJB150");
//
//
//        //////// MUZfar Unvored //////////////////
//
//
//        data.put("Muzfargarh", "PMMA151");
//        data.put("Muzfargarh", "PMMA152");
//        data.put("Muzfargarh", "PMMB153");
//        data.put("Muzfargarh", "PMMB154");
//        data.put("Muzfargarh", "PMMB155");
//        data.put("Muzfargarh", "PMMB156");
//        data.put("Muzfargarh", "PMMB157");
//        data.put("Muzfargarh", "PMMB158");
//        data.put("Muzfargarh", "PMMB159");
//        data.put("Muzfargarh", "PMMC160");
//        data.put("Muzfargarh", "PMMC161");
//        data.put("Muzfargarh", "PMMC162");
//        data.put("Muzfargarh", "PMMC163");
//        data.put("Muzfargarh", "PMMC164");
//        data.put("Muzfargarh", "PMMC165");
//        data.put("Muzfargarh", "PMMD166");
//        data.put("Muzfargarh", "PMMG167");
//        data.put("Muzfargarh", "PMMG168");
//        data.put("Muzfargarh", "PMMJ169");
//        data.put("Muzfargarh", "PMMK170");
//        data.put("Muzfargarh", "PMMM171");
//        data.put("Muzfargarh", "PMMR172");
//        data.put("Muzfargarh", "PMMR173");
//        data.put("Muzfargarh", "PMMS174");
//        data.put("Muzfargarh", "PMMS175");
//        data.put("Muzfargarh", "PMMU176");
//        data.put("Muzfargarh", "PMMU177");
//        data.put("Muzfargarh", "PMMU178");
//        data.put("Muzfargarh", "PMMU179");
//        data.put("Muzfargarh", "PMMT180");
//        data.put("Muzfargarh", "PMKE181");
//        data.put("Muzfargarh", "PMKB182");
//        data.put("Muzfargarh", "PMKU183");
//        data.put("Muzfargarh", "PMKU184");
//        data.put("Muzfargarh", "PMKU185");
//        data.put("Muzfargarh", "PMK5186");
//        data.put("Muzfargarh", "PMK5187");
//        data.put("Muzfargarh", "PMK5188");
//        data.put("Muzfargarh", "PMK5189");
//        data.put("Muzfargarh", "PMKA190");
//        data.put("Muzfargarh", "PMKA191");
//        data.put("Muzfargarh", "PMKB192");
//        data.put("Muzfargarh", "PMKB193");
//        data.put("Muzfargarh", "PMKM194");
//        data.put("Muzfargarh", "PMKM195");
//        data.put("Muzfargarh", "PMKM196");
//        data.put("Muzfargarh", "PMKM197");
//        data.put("Muzfargarh", "PMKW198");
//        data.put("Muzfargarh", "PMKW199");
//        data.put("Muzfargarh", "PMKW200");
//        data.put("Muzfargarh", "PMK6201");
//        data.put("Muzfargarh", "PMK6202");
//        data.put("Muzfargarh", "PMJS203");
//        data.put("Muzfargarh", "PMJR204");
//        data.put("Muzfargarh", "PMJR205");
//        data.put("Muzfargarh", "PMJR206");
//        data.put("Muzfargarh", "PMJJ207");
//        data.put("Muzfargarh", "PMJJ208");
//        data.put("Muzfargarh", "PMJJ209");
//        data.put("Muzfargarh", "PMJB210");
//        data.put("Muzfargarh", "PMJV211");
//        data.put("Muzfargarh", "PMJV212");
//        data.put("Muzfargarh", "PMJV213");
//        data.put("Muzfargarh", "PMJJ214");
//        data.put("Muzfargarh", "PMJJ215");
//        data.put("Muzfargarh", "PMJS216");
//        data.put("Muzfargarh", "PMJK217");
//        data.put("Muzfargarh", "PMJK218");
//        data.put("Muzfargarh", "PMJB219");
//        data.put("Muzfargarh", "PMJB220");
//        data.put("Muzfargarh", "PMJD221");
//        data.put("Muzfargarh", "PMJU222");
//        data.put("Muzfargarh", "PMJJ223");
//        data.put("Muzfargarh", "PMJB224");
//        data.put("Muzfargarh", "PMJM225");
//        data.put("Muzfargarh", "PMAA226");
//        data.put("Muzfargarh", "PMAB227");
//        data.put("Muzfargarh", "PMAB228");
//        data.put("Muzfargarh", "PMAB229");
//        data.put("Muzfargarh", "PMAB230");
//        data.put("Muzfargarh", "PMAK231");
//        data.put("Muzfargarh", "PMAK232");
//        data.put("Muzfargarh", "PMAK233");
//        data.put("Muzfargarh", "PMAK234");
//        data.put("Muzfargarh", "PMAK235");
//        data.put("Muzfargarh", "PMAK236");
//        data.put("Muzfargarh", "PMAK237");
//        data.put("Muzfargarh", "PMAK238");
//        data.put("Muzfargarh", "PMAK239");
//        data.put("Muzfargarh", "PMAK240");
//        data.put("Muzfargarh", "PMAL241");
//        data.put("Muzfargarh", "PMAM242");
//        data.put("Muzfargarh", "PMAM243");
//        data.put("Muzfargarh", "PMAM244");
//        data.put("Muzfargarh", "PMAM245");
//        data.put("Muzfargarh", "PMAM246");
//        data.put("Muzfargarh", "PMAS247");
//        data.put("Muzfargarh", "PMAS248");
//        data.put("Muzfargarh", "PMAS249");
//        data.put("Muzfargarh", "PMAS250");
//
//
//        List<String> list = new ArrayList<>();
//
//        list.add("Select");
//        Collection<String> coll = data.get(province);
//        for (String item : coll) {
//            list.add(item);
//        }
//
//
//        return list;
//    }

}
